config/routes.rb
Brner::Application.routes.draw do
  devise_for :users
  get "welcome/index"
  get "messages/index"
  get "messages/show"
  get "messages/destroy"
  get "messages/download_attachment"

  root 'welcome#index'

end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :message_parts

  def self_destruct
    unless self.viewed
      self.update_attributes(viewed: true, destruct_on: 10.minutes.from_now)
    end
  end
end

app/models/message_part.rb
class MessagePart < ActiveRecord::Base
  belongs_to :message
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  
  has_many :messages, dependent: :destroy
  validates :email, presence: true
  before_create :build_address

  protected
  def build_address
    p dbg: [self.email, email]
    self.email = self.email + "@brner.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def index
    @user   = current_user
    @emails = @user.emails
  end

  def show
    @user  = current_user
    @email = Email.find(params["id"])
  end

  def destroy
    @email = Email.find(params["id"])
    @email.destroy
    redirect_to emails_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  def index
    @user   = current_user
    @emails = @user.messages
  end

  def show
    @user  = current_user
    @email = Message.find(params["id"])
    @email.self_destruct
    @email_parts = @email.message_parts
  end

  def destroy
    @email = Message.find(params["id"])
    @email.destroy
    redirect_to messages_path
  end

  def download_attachment
    part = MessagePart.find(params["id"])
    send_data(part.body,
                type: "#{part.mime_type}", disposition: 'attachment', filename: "#{part.filename}")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "you are setup to start receiving messages"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params["id"])
    @user.destroy
  end

  def update
  end

  def show
    @user = User.includes(:messages).find(params["id"])
    @emails = @user.messages
  end

  def edit
  end

  private
  def user_params
    params.require(:user).permit(:email)
  end 	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
  <!-- Footer -->
  
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright no one at all. Go to town.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Section 1</a></li>
            <li><a href="#">Section 2</a></li>
            <li><a href="#">Section 3</a></li>
            <li><a href="#">Section 4</a></li>
          </ul>
        </div>
      </div>
    </div> 
  </footer>

app/views/layouts/_side_nav.html.erb
<div class="small-3 columns">

  <ul class="side-nav">
    <li>
    <%= link_to welcome_index_path do %> 
       <i class="fi-home large"></i>
     <% end %>
    </li>
    <li>
    <%= link_to messages_index_path do %> 
       <i class="fi-mail large"></i>
     <% end %>
    </li>
    <li>
    <% if current_user %>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fi-skull large"></i>
      <%end%>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fi-key large"></i>
      <%end%>
    <%end%>
    </li>
  </ul>

  <p><img src="http://placehold.it/120x140&amp;text=Ad"></p>

</div>

app/views/layouts/_top_nav.html.erb
<!-- Header and Nav -->

<div class="row">
  <div class="large-12 columns">
    <h1><img src="http://placehold.it/400x800&text=Logo" /></h1>
  </div>
</div>

<!-- End Header and Nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class"small-12 columns">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "alert-box #{name}" %>
      <% end %>
    <% end %>
    </div>
    </div>
    <div class="row">
      <%= render "layouts/side_nav" %>
      <div class="small-9 columns">
        <%= yield %>
    </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/messages/destroy.html.erb
<h1>Emails#destroy</h1>
<p>Find me in app/views/emails/destroy.html.erb</p>

app/views/messages/index.html.erb
<h1>Email Messages for <%= @user.email_address%></h1>
<table >
  <tr>
    <th width="250">To</th>
    <th width="250">From</th>
    <th width="250">Subject</th>
    <th width="250">Sent AT</th>
  </tr>

  <% @emails.each do |email| %>
    <tr>
      <td><%= email.recipients %></td>
      <td><%= link_to email.sender, messages_show_path(id: email.id) %></td>
      <td><%= email.subject %></td>
      <td><%= email.created_at %></td>
    </tr>
  <% end %>
</table>
<div class="pagination-centered">
  <!-- <#%= paginate @emails %> -->
</div>

app/views/messages/show.html.erb
<h1>Email Message for <%= @user.email%></h1>
<table >
  <tr>
    <th width="250">To</th>
    <th width="250">From</th>
    <th width="250">Subject</th>
    <th width="250">Sent AT</th>
  </tr>

    <tr>
      <td><%= @email.recipients %></td>
      <td><%= @email.sender %></td>
      <td><%= @email.subject %></td>
      <td><%= @email.created_at %></td>
    </tr>
</table>

<h1>-------------------------------------------------</h1>
<% if @email_parts %>
  <% @email_parts.each do |part| %>
    <% if part.mime_type == "text/plain" %>
      <h3>Message</h3>
      <div class="panel"><%= raw part.body %></div>
    <% else %>
      <h3>Attachment</h3>
      <%= link_to part.filename, messages_download_attachment_path(id: part.id) %>
      <%= ("<img src='data:#{part.mime_type};base64,%s'>" % Base64.encode64(part.body)).html_safe %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation" class="alert-box alert">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> 
          prohibited this user from being saved:
        </h2>

        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <fieldset>
      <legend>New User</legend>
      <%= f.label :email_address %> </br>
      <%= f.text_field :email_address, placeholder: "foo1234" %>@brner.com
      </br>
      <div class="row">
        <div class="large-12 large-offset-8 columns">
          <%= f.submit nil, class: "button success radius" %>
        </div>
      </div>
    </fieldset>
  <% end %>

</div>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/new.html.erb
<h1>User#new</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1>User#show</h1>
<h1><%= @user.email_address%></h1>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>

app/views/welcome/index.html.erb
<div class="large-12 columns">
  <img src="http://fc04.deviantart.net/fs17/f/2007/211/e/c/Red_Hot_Coiled_Stove_Burner_4_by_FantasyStock.jpg">
  <hr>
</div>